# SPDX-License-Identifier: Apache-2.0
# Keep official Media implementations and reviewed fixes in the build tree.
# No team change is left in the manifest checkout.
function(bkvoice_apply_media_patches)
  set(source "${NUTTX_APPS_DIR}/frameworks/multimedia/media")
  set(output "${CMAKE_BINARY_DIR}/bkvoice-media")
  set(patch_root "${NUTTX_DIR}/../vendor/beken/frameworks/patches/media")
  set(files client/media_graph.c server/audio_graph.c server/media_player.c)
  set(patches 0002-stream-io-lifetime.patch
              0003-wait-for-audio-route-format.patch
              0004-graph-error-recovery-progress.patch
              0005-player-eof-drain.patch)
  if(CONFIG_MEDIA_TRIGGER)
    list(APPEND files server/media_trigger.c)
    list(APPEND patches 0001-trigger-resource-lifetime.patch)
  endif()
  foreach(item IN LISTS files)
    get_filename_component(directory "${item}" DIRECTORY)
    file(MAKE_DIRECTORY "${output}/${directory}")
    configure_file("${source}/${item}" "${output}/${item}" COPYONLY)
  endforeach()
  find_package(Git REQUIRED)
  foreach(name IN LISTS patches)
    set(patch "${patch_root}/${name}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${patch}")
    execute_process(COMMAND "${GIT_EXECUTABLE}" apply --check "${patch}"
                    WORKING_DIRECTORY "${output}" RESULT_VARIABLE result
                    ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Media patch no longer applies (${name}): ${error}")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" apply "${patch}"
                    WORKING_DIRECTORY "${output}" RESULT_VARIABLE result
                    ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Media patch failed (${name}): ${error}")
    endif()
  endforeach()
  get_target_property(root libmedia SOURCE_DIR)
  get_target_property(sources libmedia SOURCES)
  foreach(replacement IN LISTS files)
    set(updated)
    set(count 0)
    foreach(item IN LISTS sources)
      get_filename_component(absolute "${item}" ABSOLUTE BASE_DIR "${root}")
      if(absolute STREQUAL "${source}/${replacement}")
        list(APPEND updated "${output}/${replacement}")
        math(EXPR count "${count} + 1")
      else()
        list(APPEND updated "${item}")
      endif()
    endforeach()
    if(NOT count EQUAL 1)
      message(FATAL_ERROR "Expected one official Media ${replacement}, got ${count}")
    endif()
    set(sources "${updated}")
  endforeach()
  set_property(TARGET libmedia PROPERTY SOURCES "${sources}")
  target_include_directories(libmedia PRIVATE "${source}/server" "${source}/client")
endfunction()
cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL bkvoice_apply_media_patches)
