# SPDX-License-Identifier: Apache-2.0

# BK7258 SDK bundle selector shared by the board and chip CMake files.

if(DEFINED BK7258_SDK_BUNDLES_CMAKE_INCLUDED)
  return()
endif()
set(BK7258_SDK_BUNDLES_CMAKE_INCLUDED TRUE)

set(BK7258_SDK_SUPPORTED_BUNDLE_VERSIONS legacy v3.1.1.9)
if(DEFINED ENV{BK7258_SDK_BUNDLE_VERSION} AND
   NOT "$ENV{BK7258_SDK_BUNDLE_VERSION}" STREQUAL "")
  set(BK7258_SDK_BUNDLE_VERSION "$ENV{BK7258_SDK_BUNDLE_VERSION}")
else()
  set(BK7258_SDK_BUNDLE_VERSION v3.1.1.9)
endif()

if(NOT BK7258_SDK_BUNDLE_VERSION IN_LIST
   BK7258_SDK_SUPPORTED_BUNDLE_VERSIONS)
  message(FATAL_ERROR
    "Unsupported BK7258_SDK_BUNDLE_VERSION='${BK7258_SDK_BUNDLE_VERSION}'; "
    "supported: ${BK7258_SDK_SUPPORTED_BUNDLE_VERSIONS}")
endif()

if(CONFIG_BK7258_AP_CORE)
  set(BK7258_SDK_ROLE ap)
else()
  set(BK7258_SDK_ROLE cp)
endif()

set(BK7258_SDK_BUNDLE_BASE
    "${NUTTX_BOARD_DIR}/bk_idk/armino_as_lib")
set(BK7258_SDK_BUNDLE_ROOT
    "${BK7258_SDK_BUNDLE_BASE}/versions/${BK7258_SDK_BUNDLE_VERSION}")
set(BK7258_SDK_ROLE_DIR
    "${BK7258_SDK_BUNDLE_ROOT}/${BK7258_SDK_ROLE}")
set(BK7258_SDK_LIBS_DIR "${BK7258_SDK_ROLE_DIR}/libs")

if(NOT IS_DIRECTORY "${BK7258_SDK_ROLE_DIR}/include" OR
   NOT IS_DIRECTORY "${BK7258_SDK_ROLE_DIR}/config" OR
   NOT IS_DIRECTORY "${BK7258_SDK_LIBS_DIR}")
  message(FATAL_ERROR
    "BK7258 ${BK7258_SDK_ROLE} SDK bundle "
    "'${BK7258_SDK_BUNDLE_VERSION}' is missing: ${BK7258_SDK_ROLE_DIR}")
endif()
