############################################################################
# BK7258 unified OTA manager command
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_BK7258_APP_OTA_AGENT_PROGNAME)
PRIORITY  = $(CONFIG_BK7258_APP_OTA_AGENT_PRIORITY)
STACKSIZE = $(CONFIG_BK7258_APP_OTA_AGENT_STACKSIZE)
MODULE    = $(CONFIG_BK7258_APP_OTA_AGENT)
MAINSRC   = ota_agent_main.c

include $(APPDIR)/Application.mk
